name = "SemioticOpt"
uuid = "a0c0fc10-8635-40d2-82ff-39f738735ee1"
authors = ["Semiotic Labs"]
version = "0.5.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.8"
